console.log("--Before initialization--");
var bankName;
console.log("Bank Name:",bankName,"Type:",typeof bankName);
console.log("--After initialaization--");
bankName = 'SBI Bank';
console.log("Bank Name:",bankName,"Type:",typeof bankName);
console.log("---------------------");
var marks = '90%';
console.log("Value of variable marks:",marks , "Data Type:",typeof marks );
console.log("-------------------");
console.log("--Before initialization");
var isWorking;
console.log(isWorking);
console.log("---After initialization--");
isWorking = true;
console.log(isWorking);
console.log("---------------------------");
var totalCount = "Hundred and Seven";
console.log("Total Count:",totalCount, "Data Type:",typeof totalCount);
var totalCount = 107;
console.log("Total Count:",totalCount, "Type:",typeof totalCount );